spring:
  application:
    name: nicht-die-bohne
  datasource:
    url: jdbc:h2:mem:mydb
    username: admin
    password: admin123
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
